version: '3'

services:
  dnsmasq-webproc:
    image: win7/dnsmasq-webproc:v0.2.2
    environment:
      HTTP_USER: recall
      HTTP_PASS: 10086
    ports: 
      - "53:53/udp"
      - "5380:8080"
    restart: always
    container_name: dnsmasq-webproc
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf

